service: myService
disabledDeprecations:
  - CODE_1 # To disable specific deprecation with code "CODE_1"
  - '*' # To disable all deprecation messages
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  patientsList:
    handler: handler.patientsList
    events:
      - http:
          path: patientes
          method: get

  registrationPatient:
    handler: handler.registrationPatient
    events:
      - http:
          path: patientes/{patientId}
          method: get
    