service: patients-registration
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  patientsList:
    handler: handler.patientsList
